import json
import requests

from togetherai.config import cfg
import sseclient

url = "https://api.together.xyz/inference"
model = "togethercomputer/llama-2-70b-chat"


def create_prompt(code):
    return f""" 
# Task Description: 
Your task is to generate comments for Python functions 

# Example
Here is an example on how you should do it - 
here is the input:
```python
def save_text_to_file(text):
    logger.info("in 2nd func")
    try:
        
        with open(cfg.transcribed_text / f"{{uuid.uuid4()}}.txt", "w") as file:
            file.write(text)
            logger.info("successful")
            return "success"
    except Exception as e:
        logger.exception("error")
        return str(e)```

This should be the output:
```python
def save_text_to_file(text):
    \"\"\"
    Saves the provided text to a file with a unique name.

    This function attempts to write the given text to a new file within the directory
    specified by `cfg.transcribed_text`. The file will have a unique name generated by
    `uuid.uuid4()`. If the operation is successful, it logs the success and returns the
    string "success". If an exception occurs, it logs the exception and returns the
    exception message as a string.

    :param text: The text to be saved to the file.
    :type text: str
    :return: "success" if the file is written successfully, otherwise the exception message.
    :rtype: str
    \"\"\"
    logger.info("in 2nd func")  # Log entry indicating the function has been entered.
    try:
        # Attempt to open a new file for writing in the directory specified by cfg.transcribed_text.
        # The filename is generated using uuid.uuid4() to ensure uniqueness.
        with open(cfg.transcribed_text / f"{{uuid.uuid4()}}.txt", "w") as file:
            file.write(text)  # Write the provided text to the file.
            logger.info("successful")  # Log entry indicating the write operation was successful.
            return "success"  # Return the string "success" to indicate success.
    except Exception as e:
        logger.exception("error")  # Log the exception with a message "error".
        return str(e)  # Return the exception message as a string.
```

# Instruction
Can you please add comments to all python functions using the reStructuredText Docstring Format for the following code.
```python
{code}
```
"""


if __name__ == "__main__":
    code = """

import comment_generator.backend.comment_files as comment
from comment_generator.configuration.config import cfg
import pathlib

def key_model(model):
    api_key = input("Give API key or put it in the .env file: ")
    if api_key == "":
        print("Please don't forget to put the key in the .env file")
    else:
        if model == 'chat-gpt':
            cfg.openai_api_key = api_key
        else:
            cfg.together_api_key = api_key


src_file_path = input("Enter code directory to be commented: ")
src_file_path = pathlib.Path(src_file_path.strip("\"")).as_posix() 
#pathlib.Path("C:\\Users\\Sayalee\\Projects\\langchain\\image_generator_bot").as_posix()
dest_file_path = input("Where do you want the commented code directory to be? please give the path of the root folder: ")
dest_file_path = pathlib.Path(dest_file_path.strip("\\"")).as_posix()
#pathlib.Path(r"C:\\Users\\Sayalee\\Projects\\commented_projects\\image_generator_bot").as_posix()

models = "\\n".join(cfg.updated_model_list)
model_to_use = input(models + "\\n chat-gpt" + "\\n choose the model you want to use: ")


"""

    prompt = create_prompt(code)

    print(f"Model: {model}")
    print(f"Prompt: {repr(prompt)}")
    print("Response:")
    print()

    payload = {
        "model": "togethercomputer/llama-2-70b-chat",
        "max_tokens": 512,
        "prompt": create_prompt(code),
        "request_type": "language-model-inference",
        "temperature": 0,
        "top_p": 0.7,
        "top_k": 50,
        "repetition_penalty": 1,
        "stream_tokens": True,
        "stop": ["[/INST]", "</s>"],
        "negative_prompt": "",
        "sessionKey": "2e59071178ae2b05e68015136fb8045df30c3680",
        "type": "chat",
        "prompt_format_string": "[INST]  {prompt}\n [/INST]",
        "safety_model": "",
        "repetitive_penalty": 1,
    }
    headers = {
        "accept": "application/json",
        "content-type": "application/json",
        "Authorization": f"Bearer {cfg.together_api_key}",
    }

    response = requests.post(url, json=payload, headers=headers, stream=True)
    response.raise_for_status()

    client = sseclient.SSEClient(response)
    for event in client.events():
        if event.data == "[DONE]":
            break

        partial_result = json.loads(event.data)
        token = partial_result["choices"][0]["text"]
        print(token, end="", flush=True)
